name: tf_deploy
on:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - "opened"
      - "synchronize"

defaults:
  run:
    working-directory: infra

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tf_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      
      - run: |
          terraform init
        id: init

      - run: |
          terraform fmt
        id: fmt
      
      - run: |
          terraform plan --no-color
        id: plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_access_key }}
          AWS_REGION: ${{ secrets.aws_region }}
      
      - run: |
          terraform apply --no-color -auto-approve
        id: apply
        if: github.event.pull_request.merged == true
        env:
          AWS_ACCESS_KEY_ID: ${{ secret.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secret.aws_access_key }}

