name: tf_destory
on:
  workflow_dispatch: 
      
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
    
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  tf_destory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true

      - run: |
          cd lambda
          GOOS=linux go build -o ../infra/main
        name: Go build

      - uses: hashicorp/setup-terraform@v2
        name: Terraform setup
      
      - run: |
          terraform init
        id: init
        name: Terraform init
        working-directory: infra
      
      - run: |
          terraform plan -no-color
        id: plan
        name: Terraform plan
        working-directory: infra

      
      - run: |
          terraform destroy -no-color -auto-approve
        id: destroy
        name: Terraform destroy
        working-directory: infra
