name: tf_destory
on:
  workflow_dispatch:
    
      
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: infra
    

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  tf_destory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        name: Terraform setup
      
      - run: |
          terraform init
        id: init
        name: Terraform init
      
      - run: |
          terraform plan -no-color
        id: plan
        continue-on-error: true
        name: Terraform plan
      
      - run: |
          terraform destroy -no-color -auto-approve
        id: destroy
        name: Terraform destroy